apiVersion: v1
kind: BuildConfig
metadata:
  name: '[[containerId]]'
  labels:
    app: NFA
spec:
  triggers:
    - type: Generic
      generic:
        secret: 9238a7966e062fe0
    - type: ConfigChange
  runPolicy: Serial
  source:
    type: Git
    contextDir: "./"
    git:
      uri: '[[gitRepository]]'
      ref: master
    sourceSecret:
      name: '[[gitCredentialsId]]'
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: '[[containerId]]:latest'
