apiVersion: v1
kind: Service
metadata:
  name: '[[containerId]]'
  labels:
    app: '[[containerId]]'
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name":"[[containerId]]","namespace":"[[ocpProject]]","kind":"Service"}]'
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: '[[containerId]]'
  type: ClusterIP
  sessionAffinity: None
